### PR TITLE
minify html output by jekyll-compress-html@3.0.2

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This will minify the html page output, take homepage as example result:

Minified: 11 KB
Unminified: 17 KB

Minified + gzip level 6 compressed : 4.5 KB
Unminified + gzip level 6 compressed: 4.9 KB

Both minified files are much smaller.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pofeng are we good to go?

**Comment by pofeng** [comment]
@PeterDaveHello 看起很棒, 等我幾天, 等大概懂語法後, 教會 @snoopy60313 @Rockhung @ttcat , 
就會 merge , 因為我怕 merge 後, 我就忘記語法了 XD

會擋到你後面的 patch 嗎 ?

 CC: @ETBlue

**Comment by PeterDaveHello** [comment]
> 會擋到你後面的 patch 嗎 ?

nope

**Comment by PeterDaveHello** [comment]
Reference: https://github.com/penibelst/jekyll-compress-html

**Comment by PeterDaveHello** [comment]
This won't affect the workflow or other syntax, just need to use the compress layout.

**Comment by pofeng** [comment]
ok 我週五應該就會告訴大家 然後 merge

**Comment by PeterDaveHello** [comment]
:+1: 
http://ocf.tw/ is now faster loaded!

**Comment by pofeng** [comment]
感謝 @PeterDaveHello 大大的 PR !!

**Pull request merged**
